# Generated by Django 5.2.13 on 2026-05-01 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetronomeCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metronome_id", models.CharField(db_index=True, max_length=255)),
                (
                    "metronome_environment",
                    models.CharField(default="sandbox", max_length=32),
                ),
                ("metronome_livemode", models.BooleanField(default=False)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_synced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "sync_cursor",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "sync_origin",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "sync_event_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("ingest_aliases", models.JSONField(blank=True, default=list)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("metronome_id", "metronome_environment")},
            },
        ),
    ]
