# Generated by Django 5.2.13 on 2026-05-01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_metronome", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="metronomecustomer",
            index=models.Index(
                fields=["metronome_environment", "name"],
                name="django_metr_metrono_4524f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metronomecustomer",
            index=models.Index(
                fields=["metronome_environment", "archived_at"],
                name="django_metr_metrono_a58816_idx",
            ),
        ),
        migrations.CreateModel(
            name="SyncCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity", models.CharField(max_length=64)),
                (
                    "metronome_environment",
                    models.CharField(default="sandbox", max_length=32),
                ),
                ("cursor", models.CharField(blank=True, default="", max_length=255)),
                ("window_start", models.DateTimeField(blank=True, null=True)),
                ("window_end", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="idle", max_length=32)),
                ("last_error", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("last_successful_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="MetronomeRateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metronome_id", models.CharField(db_index=True, max_length=255)),
                (
                    "metronome_environment",
                    models.CharField(default="sandbox", max_length=32),
                ),
                ("metronome_livemode", models.BooleanField(default=False)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_synced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "sync_cursor",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "sync_origin",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "sync_event_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"unique_together": {("metronome_id", "metronome_environment")}},
        ),
        migrations.CreateModel(
            name="MetronomeContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metronome_id", models.CharField(db_index=True, max_length=255)),
                (
                    "metronome_environment",
                    models.CharField(default="sandbox", max_length=32),
                ),
                ("metronome_livemode", models.BooleanField(default=False)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_synced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "sync_cursor",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "sync_origin",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "sync_event_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("status", models.CharField(blank=True, default="", max_length=64)),
                ("starting_at", models.DateTimeField(blank=True, null=True)),
                ("ending_before", models.DateTimeField(blank=True, null=True)),
                (
                    "rate_card_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="django_metronome.metronomecustomer",
                    ),
                ),
            ],
            options={"unique_together": {("metronome_id", "metronome_environment")}},
        ),
        migrations.CreateModel(
            name="MetronomeInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metronome_id", models.CharField(db_index=True, max_length=255)),
                (
                    "metronome_environment",
                    models.CharField(default="sandbox", max_length=32),
                ),
                ("metronome_livemode", models.BooleanField(default=False)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_synced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "sync_cursor",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "sync_origin",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "sync_event_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("status", models.CharField(blank=True, default="", max_length=64)),
                (
                    "total",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=16)),
                ("start_timestamp", models.DateTimeField(blank=True, null=True)),
                ("end_timestamp", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="django_metronome.metronomecustomer",
                    ),
                ),
            ],
            options={"unique_together": {("metronome_id", "metronome_environment")}},
        ),
        migrations.CreateModel(
            name="MetronomeUsageAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metronome_environment",
                    models.CharField(default="sandbox", max_length=32),
                ),
                (
                    "event_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("window_size", models.CharField(default="day", max_length=32)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                (
                    "value",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                ("groups", models.JSONField(blank=True, default=dict)),
                (
                    "grouping_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "last_synced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_aggregates",
                        to="django_metronome.metronomecustomer",
                    ),
                ),
            ],
            options={},
        ),
        migrations.CreateModel(
            name="MetronomeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_id", models.CharField(max_length=255)),
                (
                    "product_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("starting_at", models.DateTimeField(blank=True, null=True)),
                ("ending_before", models.DateTimeField(blank=True, null=True)),
                ("pricing_group_values", models.JSONField(blank=True, default=dict)),
                ("rate_payload", models.JSONField(blank=True, default=dict)),
                (
                    "rate_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="django_metronome.metronomeratecard",
                    ),
                ),
            ],
            options={},
        ),
        migrations.AddConstraint(
            model_name="synccheckpoint",
            constraint=models.UniqueConstraint(
                fields=("entity", "metronome_environment"),
                name="uniq_checkpoint_entity_environment",
            ),
        ),
        migrations.AddIndex(
            model_name="metronomeratecard",
            index=models.Index(
                fields=["metronome_environment", "name"],
                name="django_metr_metrono_9a3bd4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metronomecontract",
            index=models.Index(
                fields=["metronome_environment", "status"],
                name="django_metr_metrono_7d4ca7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metronomecontract",
            index=models.Index(
                fields=["customer", "starting_at"],
                name="django_metr_metrono_d4f154_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metronomeinvoice",
            index=models.Index(
                fields=["metronome_environment", "status"],
                name="django_metr_metrono_a3b77f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metronomeinvoice",
            index=models.Index(
                fields=["customer", "start_timestamp"],
                name="django_metr_metrono_57af99_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="metronomeusageaggregate",
            constraint=models.UniqueConstraint(
                fields=(
                    "metronome_environment",
                    "customer",
                    "event_type",
                    "window_size",
                    "window_start",
                    "window_end",
                    "grouping_key",
                ),
                name="uniq_usage_aggregate_dimensions",
            ),
        ),
        migrations.AddIndex(
            model_name="metronomeusageaggregate",
            index=models.Index(
                fields=["metronome_environment", "event_type", "window_start"],
                name="django_metr_metrono_76f7c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metronomeusageaggregate",
            index=models.Index(
                fields=["customer", "window_start"],
                name="django_metr_metrono_6ce89e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="metronomerate",
            constraint=models.UniqueConstraint(
                fields=("rate_card", "product_id", "starting_at"),
                name="uniq_rate_card_product_starting_at",
            ),
        ),
        migrations.AddIndex(
            model_name="metronomerate",
            index=models.Index(
                fields=["product_id", "starting_at"],
                name="django_metr_product_b3f825_idx",
            ),
        ),
    ]
