# Generated by Django 5.2.13 on 2026-05-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_metronome", "0002_core_sync_mvp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metronomeratecard",
            name="metronome_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=(
                    "Optional. Leave blank for admin-created cards; "
                    "a local placeholder id is assigned automatically."
                ),
                max_length=255,
            ),
        ),
    ]
