# Generated by Django 5.2.13 on 2026-05-02 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_metronome", "0004_rate_card_metronome_id_required"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="metronomecontract",
            new_name="django_metr_metrono_207838_idx",
            old_name="django_metr_metrono_7d4ca7_idx",
        ),
        migrations.RenameIndex(
            model_name="metronomecontract",
            new_name="django_metr_custome_9995c8_idx",
            old_name="django_metr_metrono_d4f154_idx",
        ),
        migrations.RenameIndex(
            model_name="metronomecustomer",
            new_name="django_metr_metrono_5e16ec_idx",
            old_name="django_metr_metrono_4524f0_idx",
        ),
        migrations.RenameIndex(
            model_name="metronomecustomer",
            new_name="django_metr_metrono_6af44b_idx",
            old_name="django_metr_metrono_a58816_idx",
        ),
        migrations.RenameIndex(
            model_name="metronomeinvoice",
            new_name="django_metr_metrono_e551f9_idx",
            old_name="django_metr_metrono_a3b77f_idx",
        ),
        migrations.RenameIndex(
            model_name="metronomeinvoice",
            new_name="django_metr_custome_1f4db1_idx",
            old_name="django_metr_metrono_57af99_idx",
        ),
        migrations.RenameIndex(
            model_name="metronomerate",
            new_name="django_metr_product_8c027a_idx",
            old_name="django_metr_product_b3f825_idx",
        ),
        migrations.RenameIndex(
            model_name="metronomeratecard",
            new_name="django_metr_metrono_3ced00_idx",
            old_name="django_metr_metrono_9a3bd4_idx",
        ),
        migrations.RenameIndex(
            model_name="metronomeusageaggregate",
            new_name="django_metr_metrono_65bd70_idx",
            old_name="django_metr_metrono_76f7c9_idx",
        ),
        migrations.RenameIndex(
            model_name="metronomeusageaggregate",
            new_name="django_metr_custome_a216f3_idx",
            old_name="django_metr_metrono_6ce89e_idx",
        ),
    ]
